spring:
  application:
    name: product-order-service
  jpa:
    show-sql: true # ????? ?????
    properties:
      hibernate:
        format_sql: true # SQL ???
        highlight_sql: true # ANSI ??? ?? ????
        use_sql_comments: true # SQL ??? /* */ ?? ??


logging:
  level:
    org.hibernate.SQL: debug # logger? ?????
    org.hibernate.type.descriptor.sql: trace # ???? ? ??